### ISSUE TITLE
Call backs not triggered

### ISSUE THREAD

**Issue by LScodeblack** [SongJiaqiang/seatsio-flutter#8]
Call back actions in Flutter aren't being triggered, print function dosent run 

![Screenshot 2023-03-16 at 12 57 15](https://user-images.githubusercontent.com/128048109/225609757-175b1702-2fbb-4d4a-83a5-bbfaaf4ca762.png)
![Screenshot 2023-03-16 at 12 57 04](https://user-images.githubusercontent.com/128048109/225609764-f416fc95-c934-49c3-b545-ffb435e65081.png)
![Screenshot 2023-03-16 at 12 56 47](https://user-images.githubusercontent.com/128048109/225609769-60416f1e-8695-4cf9-a68d-2c8da42c8910.png)

**Comment by SongJiaqiang** [comment]
I'm sorry about that, my code works fine.
If your problem is still not solved, you can paste some more code and I will try to help you find the source of the problem.
![Mar-17-2023 15-50-48](https://user-images.githubusercontent.com/5006599/225845586-5833d785-adb1-43c1-920c-fcf2b5e6d333.gif)
